### ISSUE TITLE
Issue while preprocessing recipes5k

### ISSUE THREAD

**Issue by VimalKumarKJ** [Cheng-K/FoodNet#1]
Like when i preprocess the ipynb file for recipes5k
![image](https://github.com/Cheng-K/FoodNet/assets/76762337/b08c89c7-7090-4042-8682-6a1034e85666)
it shows this error

**Comment by Cheng-K** [comment]
Hi @VimalKumarKJ, this is most probably due to you are not having the file located at that path. Did you follow the steps to download the nutrition5k datasets which includes the ingredients_metadata.csv?

**Comment by VimalKumarKJ** [comment]
Yea bro....I did it wonderful work btw.....I would like to be ur pupil mann

**Comment by VimalKumarKJ** [comment]
I would like to learn more ml stuffs

**Comment by VimalKumarKJ** [comment]
Am new and currently at my 4th year ug course

**Comment by Cheng-K** [comment]
Sounds cool. All the best in your course and we can keep in touch 🙂

**Comment by VimalKumarKJ** [comment]
Already landed a job in expeditors

**Comment by VimalKumarKJ** [comment]
Tqsmm bro

**Comment by VimalKumarKJ** [comment]
Do u have discord?
